# Site settings
title: Lachlan Campbell
email: hello@lachlanjc.me
description: >
  Lachlan Campbell is a front-end web designer and engineer.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://lachlanjc.me" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

sass:
  sass_dir: _sass
  style: :compressed
